### ISSUE TITLE
.deb release not working on debian stable (wrong glibc version)

### ISSUE THREAD

**Issue by ermina** [jackkilgore/EmissionControl2#57]
Installing the package from the release:
`# dpkg -i EmissionControl2_1.0-1_amd64.deb`
then executing the binary: 
`$ EmissionControl2`
results in:
`EmissionControl2: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by EmissionControl2)`

**Comment by rodneydup** [comment]
Thanks for pointing this out. I've been using Debian Testing and it hadn't occurred to me that my build would be using a very new libc version. I'm going to build with an older version of libc and upload a new release shortly.

I'll also have the debian build instructions up in the next few days. For now, if you'd like to try building it yourself, I *think* the following should work (in fact, if it does work for you, then I'll put these debian build instructions up right away!):

- Make sure you have CMake 3.10 or newer.
- Run the following in a terminal to install the necessary libraries for building:
`sudo apt install libgtk-3-dev libasound2-dev libsndfile1-dev libfftw3-dev libjack-dev`
- git clone the repository
- cd into EmissionControl2/ecSource
- run `./scripts/configure.sh`
- run `./scripts/run.sh`

**Comment by rodneydup** [comment]
This should now be fixed in the new release (1.01) https://github.com/jackkilgore/EmissionControl2/releases/tag/v1.01

There are also build instructions now listed in the README.
